### ISSUE TITLE
Fails to set an image

### ISSUE THREAD

**Issue by humdingerb** [augiedoggie/bgswitch#1]
I already have one image set for all workspaces. Setting another with bgswitch doesn't work. Even just listing the backgrounds fails:

```
 1 $> bgswitch -d -v -w 1 list
BMessage(0x0) {
        be:bgndimginfoerasetext = bool(false)
        be:bgndimginfopath = string("/boot/home/Tumble Leaves.png", 29 bytes)
        be:bgndimginfoworkspaces = int32(0xffffffff or 4294967295)
        be:bgndimginfooffset = BPoint(x:0, y:0)
        be:bgndimginfomode = int32(0x1 or 1)
        be:bgndimginfoset = int32(0x0 or 0)
}
Workspace: 1
Error: Workspace not found in BMessage
File: No background set!
File: 
Mode: Scaled
Offset: X=0 Y=0
Text Outline: true
```

Maybe something off with my "Desktop" folder? It's attached as zip archive.
[desktop.zip](https://github.com/augiedoggie/bgswitch/files/14628202/desktop.zip)

**Comment by augiedoggie** [comment]
> Maybe something off with my "Desktop" folder? It's attached as zip archive. [desktop.zip](https://github.com/augiedoggie/bgswitch/files/14628202/desktop.zip)

No, it's a bug/limitation of the app.  It wasn't handling a "global background" properly and was expecting each workspace to have a separate wallpaper.  I've partially fixed the problem with the `list` command but I probably need to do some more work on the `set` and `clear` commands.

**Comment by augiedoggie** [comment]
I think the basics are working now.  Still need to do some more testing and add a command line option for completely clearing a wallpaper and setting it back to the global, but I don't even think the regular `Backgrounds` application in Haiku can do that.

**Comment by humdingerb** [comment]
Thanks for the quick fix!
I can confirm it's working for me now. I can list the backgrounds, and set images for a single and all workspaces.
